apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  # The name of the task
  name: bind-iam-app-task
spec:
  params:
  resources:
    inputs:
    - name: image
      type: image
      # The output resource(s) of the task, such as an image built from the source code
  steps:
    - name: iam
      image: gcr.io/cloud-builders/gcloud
      args:
      - run
      - services
      - add-iam-policy-binding
      - my-example-app
      - --member="allUsers"
      - --role="roles/run.invoker"
      - --region=us-central1
      - --platform=managed