apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  # The name of the task
  name: deploy-app-task
spec:
  params:
  resources:
    inputs:
      # The input resource(s) of the task, such as a GitHub repository
  steps:
    # Each step of the task