apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitlab-pipeline
spec:
  resources:
  - name: git
    type: git
  - name: image
    type: image
  tasks:
    # The names of tasks in this pipeline
  - name: build-gitlab-app
    taskRef:
      # The name of the task
      name: build-gitlab-app-task
    resources:
      inputs:
      - name: git
        resource: git
      outputs:
      - name: image
        resource: image
  - name: deploy-gitlab-app
    taskRef:
      # The name of the task
      name: deploy-gitlab-app-task
    resources:
      inputs:
      - name: image
        resource: image