apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-gitlab-app-task
spec:
  params:
    - name: dockerfilePath
      type: string
      description: The path to the dockerfile to build
      default: /workspace/git/app/python/Dockerfile
    - name: srcPath
      type: string
      description: The path to the source code
      default: /workspace/git/app/python
    - name: kanikoContextPath
      type: string
      description: Kaniko build context
      default: /workspace/git/app/python
  resources:
    inputs:
      - name: git
        type: git
    outputs:
      - name: gitlab-image
        type: image
  steps:
  - name: pytest
    image: python
    command:
      - /bin/bash
      - -c
    args: ["cd", "(params.srcPath)", "&&", "pip3", "install", "-r", "requirements.txt", "&&", "pip3", "install", "r", "dev_requirements.txt", "&&", "pytest", "."]
  - name: kaniko
    image: gcr.io/kaniko-project/executor
    env:
      - name: DOCKER_CONFIG
        value: /builder/home/.docker/
    command:
      - /kaniko/executor
    args: ["/kaniko/executor", "--dockerfile=$(params.dockerfilePath)", "--destination=$(resources.outputs.image.url", "--context=$(params.kanikoContextPath)"]
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  # The name of the task
  name: deploy-gitlab-app-task
spec:
  params:
  resources:
    inputs:
    - name: gitlab-image
      type: image
      # The output resource(s) of the task, such as an image built from the source code
  steps:
    - name: run
      image: gcr.io/cloud-builders/gcloud
      args:
      - beta
      - run
      - deploy
      - default
      - --image=$(inputs.resources.image.url)
      - --region=us-central1
      - --platform=managed
      - --allow-unauthenticated