imports:
- path: instance.jinja
- path: ../workshop-staging.sh
  name: workshop-staging.sh

resources:
- name: my-instance
  type: instance.jinja
  properties:
    metadata-from-file:
      startup-script: workshop-staging.sh
    zone: ZONE_TO_RUN