apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: gitlab-pipeline
spec:
  resources:
  - name: gitlab-repo
    type: git
  - name: gitlab-image
    type: image
  tasks:
    # The names of tasks in this pipeline
  - name: build-gitlab-app
    taskRef:
      # The name of the task
      name: build-gitlab-app-task
    resources:
      inputs:
      - name: gitlab-repo
        resource: gitlab-repo
      outputs:
      - name: gitlab-image
        resource: gitlab-image
  - name: deploy-gitlab-app
    taskRef:
      # The name of the task
      name: deploy-gitlab-app-task
    resources:
      inputs:
      - name: gitlab-image
        resource: gitlab-image