apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  # The name of the pipeline resource
  name: gitlab-repo
spec:
  type: git
  params:
  # The revision/branch of the repository
  - name: revision
    value: main
  # The URL of the repository
  - name: url
    value: YOUR_GITLAB_HERE
